spring.application.name=hotel

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lab3
spring.datasource.username=kreker1207
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Configure connection pool settings
spring.sql.init.mode=always
spring.datasource.hikari.maximum-pool-size=10

# Hibernate (JPA) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none