services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kreker1207
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab3
    volumes:
      - db_data:/var/lib/postgresql/data   # Persistent storage
      - ./src/main/resources/static/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: